### ISSUE TITLE
Error on getting archive data from device

### ISSUE THREAD

**Issue by PAvdVeer** [MarcoGos/PyVantagePro#2]
When I try to get archive data from my Vantage Pro 2+ in python 3.11.2 on Raspberry Pi 4 with RpiOS Bookworm, I get the following traceback (the code I've executed is "data = device.get_archives()"):

> Traceback (most recent call last):
>   File "/home/user/MyDavisWeatherStation.py", line 3, in <module>
>     data = device.get_archives()
>   File "/home/user/.local/lib/python3.11/site-packages/pyvantagepro/device.py", line 199, in get_archives
>     for item in generator:
>   File "/home/user/.local/lib/python3.11/site-packages/pyvantagepro/device.py", line 212, in _get_archives_generator
>     period = self.archive_period
>   File "/home/user/.local/lib/python3.11/site-packages/pyvantagepro/utils.py", line 66, in __get__
>     value = self.func(obj)
>   File "/home/user/.local/lib/python3.11/site-packages/pyvantagepro/device.py", line 292, in archive_period
>     return struct.unpack(b'B', self.read_from_eeprom("2D", 1))[0]
>   File "/home/user/.local/lib/python3.11/site-packages/pyvantagepro/utils.py", line 93, in wrapped_f
>     raise e
>   File "/home/user/.local/lib/python3.11/site-packages/pyvantagepro/utils.py", line 85, in wrapped_f
>     ret = f(*args, **kwargs)
>   File "/home/user/.local/lib/python3.11/site-packages/pyvantagepro/device.py", line 146, in read_from_eeprom
>     if VantageProCRC(data).check():
>   File "/home/user/.local/lib/python3.11/site-packages/pyvantagepro/parser.py", line 79, in check
>     if len(self.data) != 0 and self.checksum == 0:
>   File "/home/user/.local/lib/python3.11/site-packages/pyvantagepro/utils.py", line 66, in __get__
>     value = self.func(obj)
>   File "/home/user/.local/lib/python3.11/site-packages/pyvantagepro/parser.py", line 66, in checksum
>     for byte in array(str('B'), bytes(self.data)):
> TypeError: string argument without an encoding

Am I doing something wrong? Or is this a compatibility issue with python 3.11?
The complete code I'm using so far is:

```
from pyvantagepro import VantagePro2
device = VantagePro2.from_url('serial:/dev/ttyUSB0:19200:8N1')
data = device.get_archives()
```

Thank you in advance

**Comment by MarcoGos** [comment]
@PAvdVeer Sorry for my very late response. I probably missed the email notification. About your question, you need to provide a start datetime and end datetime as params like:

end_datetime = datetime.now()
start_datetime = end_datetime - timedelta(
    minutes=20
)
get_archives(start_datetime, end_datetime)

The number of minutes must be at least the value of the period interval.
